version: '3'
services:
    api-herois:
        build: .
        ports:
            - 3000:3000
        environment: 
            MONGO_URL: mongodb
            PORT: 4000

        depends_on: 
            - mongodb
        links: 
            - mongodb
            
    mongodb: 
        image: mongo:3.5
        ports: 
            - 27017:2017   